#include "hkx_451_writer.h"

#include <stdio.h>

#include <vector>

#include <Animation/Animation/Mapper/hkaSkeletonMapper.h>
#include <Animation/Animation/hkaAnimationContainer.h>
#include <Animation/Ragdoll/Instance/hkaRagdollInstance.h>
#include <Common/Base/Container/Array/hkArray.h>
#include <Common/Base/Reflection/hkClass.h>
#include <Common/Base/Reflection/hkClassMember.h>
#include <Common/Base/Reflection/hkInternalClassMember.h>
#include <Common/Base/System/Io/OStream/hkOStream.h>
#include <Common/Serialize/Packfile/Binary/hkBinaryPackfileWriter.h>
#include <Common/Serialize/Packfile/hkPackfileWriter.h>
#include <Common/Serialize/Util/hkRootLevelContainer.h>
#include <Common/Serialize/Util/hkStructureLayout.h>
#include <Physics/Utilities/Serialize/hkpPhysicsData.h>

#include "legacy_class_cloner.h"
#include "ragdoll_legacy_motion.h"

namespace
{
	static const char* const kTargetVersion = "Havok-4.5.1-r1";

	struct LegacyEnvironmentVariable
	{
		const char* m_name;
		const char* m_value;
	};

	struct LegacyEnvironment
	{
		hkArray<LegacyEnvironmentVariable> m_variables;
	};

	static hkInternalClassMember g_environmentVariableMembers[] =
	{
		{ "name", HK_NULL, HK_NULL, hkClassMember::TYPE_CSTRING, hkClassMember::TYPE_VOID, 0, 0, HK_OFFSET_OF(LegacyEnvironmentVariable, m_name), HK_NULL },
		{ "value", HK_NULL, HK_NULL, hkClassMember::TYPE_CSTRING, hkClassMember::TYPE_VOID, 0, 0, HK_OFFSET_OF(LegacyEnvironmentVariable, m_value), HK_NULL },
	};

	hkClass g_environmentVariableClass(
		"hkxEnvironmentVariable",
		HK_NULL,
		sizeof(LegacyEnvironmentVariable),
		HK_NULL,
		0,
		HK_NULL,
		0,
		reinterpret_cast<const hkClassMember*>(g_environmentVariableMembers),
		HK_COUNT_OF(g_environmentVariableMembers),
		HK_NULL,
		HK_NULL,
		0);

	static hkInternalClassMember g_environmentMembers[] =
	{
		{ "variables", &g_environmentVariableClass, HK_NULL, hkClassMember::TYPE_ARRAY, hkClassMember::TYPE_STRUCT, 0, 0, HK_OFFSET_OF(LegacyEnvironment, m_variables), HK_NULL },
	};

	hkClass g_environmentClass(
		"hkxEnvironment",
		HK_NULL,
		sizeof(LegacyEnvironment),
		HK_NULL,
		0,
		HK_NULL,
		0,
		reinterpret_cast<const hkClassMember*>(g_environmentMembers),
		HK_COUNT_OF(g_environmentMembers),
		HK_NULL,
		HK_NULL,
		0);

	class LegacyClassListener : public hkPackfileWriter::AddObjectListener
	{
	public:
		explicit LegacyClassListener(LegacyClassCloner& cloner)
			: m_cloner(cloner)
		{
		}

		virtual void addObjectCallback(ObjectPointer& objectPointer, ClassPointer& classPointer)
		{
			(void)objectPointer;
			if (classPointer != HK_NULL)
			{
				classPointer = m_cloner.mapClass(classPointer);
			}
		}

	private:
		LegacyClassCloner& m_cloner;
	};

	void populateEnvironment(LegacyEnvironment& environment)
	{
		environment.m_variables.setSize(3);
		environment.m_variables[0].m_name = "modeller";
		environment.m_variables[0].m_value = "Blender 4.3";
		environment.m_variables[1].m_name = "configuration";
		environment.m_variables[1].m_value = "Default";
		environment.m_variables[2].m_name = "infoString";
		environment.m_variables[2].m_value = "Generated by dow2_tools ragdoll_workspace";
	}
}

bool writeRagdollGraphAs451(const RagdollBuildResult& buildResult, const char* outputFile)
{
	if (outputFile == HK_NULL
		|| buildResult.animationContainer == HK_NULL
		|| buildResult.physicsData == HK_NULL
		|| buildResult.ragdollInstance == HK_NULL
		|| buildResult.ragdollToAnimationMapper == HK_NULL
		|| buildResult.animationToRagdollMapper == HK_NULL)
	{
		return false;
	}

	printf("Preparing legacy class mapping...\n");
	fflush(stdout);
	LegacyClassCloner cloner;
	MotionClassOverride motionOverride;
	cloner.setOverride(&motionOverride);
	const hkClass* animationContainerClass = cloner.mapClass(&hkaAnimationContainerClass);
	const hkClass* physicsDataClass = cloner.mapClass(&hkpPhysicsDataClass);
	const hkClass* ragdollInstanceClass = cloner.mapClass(&hkaRagdollInstanceClass);
	const hkClass* skeletonMapperClass = cloner.mapClass(&hkaSkeletonMapperClass);

	printf("Preparing legacy root container...\n");
	fflush(stdout);
	LegacyEnvironment environment;
	populateEnvironment(environment);

	hkRootLevelContainer root;
	root.m_namedVariants = hkAllocate<hkRootLevelContainer::NamedVariant>(6, HK_MEMORY_CLASS_SERIALIZE);
	root.m_numNamedVariants = 6;
	root.m_namedVariants[0].set("Environment Data", &environment, &g_environmentClass);
	root.m_namedVariants[1].set("Animation Container", buildResult.animationContainer, animationContainerClass);
	root.m_namedVariants[2].set("Physics Data", buildResult.physicsData, physicsDataClass);
	root.m_namedVariants[3].set("RagdollInstance", buildResult.ragdollInstance, ragdollInstanceClass);
	root.m_namedVariants[4].set("SkeletonMapper", buildResult.ragdollToAnimationMapper, skeletonMapperClass);
	root.m_namedVariants[5].set("SkeletonMapper", buildResult.animationToRagdollMapper, skeletonMapperClass);

	printf("Configuring packfile writer...\n");
	fflush(stdout);
	std::vector<MotionOverflowSave> motionSaves;
	marshalMotionsTo451(buildResult.rigidBodies, motionSaves);
	LegacyClassListener listener(cloner);
	hkBinaryPackfileWriter writer;
	writer.setContents(&root, hkRootLevelContainerClass, &listener);

	hkPackfileWriter::Options options;
	options.m_layout = hkStructureLayout::MsvcWin32LayoutRules;
	options.m_writeMetaInfo = true;
	options.m_contentsVersion = kTargetVersion;

	printf("Opening output stream...\n");
	fflush(stdout);
	hkOstream stream(outputFile);
	if (!stream.isOk())
	{
		restoreMotionOverflows(motionSaves);
		fprintf(stderr, "Error: cannot open %s for writing\n", outputFile);
		return false;
	}

	printf("Saving packfile...\n");
	fflush(stdout);
	if (writer.save(stream.getStreamWriter(), options) != HK_SUCCESS)
	{
		restoreMotionOverflows(motionSaves);
		fprintf(stderr, "Error: failed to write Havok 4.5.1 ragdoll packfile\n");
		return false;
	}

	restoreMotionOverflows(motionSaves);
	return true;
}